In [31]:
#https://docs.python.org/3/library/datetime.html#
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/refs/heads/master/Python/Pandas/10-Datetime-Timeseries/ETH_1h.csv')

pd.set_option('display.max_columns', 85)
pd.set_option('display.max_rows', 85)

df.head()

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [32]:
df.loc[0, 'Date']

'2020-03-13 08-PM'

In [33]:
#turn data into by format
df['Date'] = pd.to_datetime(df['Date'], format='%Y-%m-%d %I-%p')
df['Date']

0       2020-03-13 20:00:00
1       2020-03-13 19:00:00
2       2020-03-13 18:00:00
3       2020-03-13 17:00:00
4       2020-03-13 16:00:00
                ...
23669   2017-07-01 15:00:00
23670   2017-07-01 14:00:00
23671   2017-07-01 13:00:00
23672   2017-07-01 12:00:00
23673   2017-07-01 11:00:00
Name: Date, Length: 23674, dtype: datetime64[ns]

In [34]:
#turn date into dayname
df.loc[0, 'Date'].day_name()

'Friday'

In [35]:
#format sine download
d_parser = lambda x: pd.to_datetime(x, format='%Y-%m-%d %I-%p')
df = pd.read_csv('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/refs/heads/master/Python/Pandas/10-Datetime-Timeseries/ETH_1h.csv', parse_dates=['Date'], date_parser=d_parser)

df.head()

C:\Users\Thanakrit\AppData\Local\Temp\ipykernel_22248\2765839710.py:2: FutureWarning: The argument 'date_parser' is deprecated and will be removed in a future version. Please use 'date_format' instead, or read your data in as 'object' dtype and then call 'to_datetime'.
  df = pd.read_csv('https://raw.githubusercontent.com/CoreyMSchafer/code_snippets/refs/heads/master/Python/Pandas/10-Datetime-Timeseries/ETH_1h.csv', parse_dates=['Date'], date_parser=d_parser)

                 Date  Symbol    Open    High     Low   Close      Volume
0 2020-03-13 20:00:00  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1 2020-03-13 19:00:00  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2 2020-03-13 18:00:00  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3 2020-03-13 17:00:00  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4 2020-03-13 16:00:00  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [36]:
#Add dayname
df['Dayofweek'] = df['Date'].dt.day_name()
df

,Date,Symbol,Open,High,Low,Close,Volume,Dayofweek
0,2020-03-13 20:00:00,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,Friday
1,2020-03-13 19:00:00,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,Friday
2,2020-03-13 18:00:00,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,Friday
3,2020-03-13 17:00:00,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,Friday
4,2020-03-13 16:00:00,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,Friday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [37]:
df['Date'].min()

Timestamp('2017-07-01 11:00:00')

In [38]:
df['Date'].max()

Timestamp('2020-03-13 20:00:00')

In [39]:
#time range
df['Date'].max() - df['Date'].min()

Timedelta('986 days 09:00:00')

In [40]:
#Time range
# filt = (df['Date'] >= '2019') < (df['Date'] < '2020')
filt = (df['Date'] >= pd.to_datetime('2019-01-01')) < (df['Date'] < pd.to_datetime('2019-12-31'))
df.loc[filt]

,Date,Symbol,Open,High,Low,Close,Volume,Dayofweek
10509,2018-12-31 23:00:00,ETHUSD,130.62,131.36,130.20,130.53,869026.39,Monday
10510,2018-12-31 22:00:00,ETHUSD,129.97,131.00,129.07,130.62,1972726.62,Monday
10511,2018-12-31 21:00:00,ETHUSD,130.90,130.90,129.47,129.97,1079617.65,Monday
10512,2018-12-31 20:00:00,ETHUSD,131.17,131.58,130.36,130.90,1775465.69,Monday
10513,2018-12-31 19:00:00,ETHUSD,134.83,134.90,128.50,131.17,3380282.07,Monday
...,...,...,...,...,...,...,...,...
23669,2017-07-01 15:00:00,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,Saturday
23670,2017-07-01 14:00:00,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,Saturday
23671,2017-07-01 13:00:00,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,Saturday
23672,2017-07-01 12:00:00,ETHUSD,275.01,275.01,271.00,274.83,824362.87,Saturday
23673,2017-07-01 11:00:00,ETHUSD,279.98,279.99,272.10,275.01,679358.87,Saturday

In [41]:
df.set_index('Date', inplace=True)

In [50]:
df.sort_index(inplace=True)

In [54]:
df['2020-01':'2020-02']['Close'].mean()

np.float64(195.1655902777778)

In [62]:
df.loc['2020-01-01']['High'].max()

np.float64(132.68)

In [64]:
#Max in a day
highs = df['High'].resample('D').max()
highs['2020-01-01']

np.float64(132.68)

In [72]:
#Resample as many condition
df.resample('W').agg({'Close': 'mean', 'High': 'max', 'Low': 'min', 'Volume': 'sum'})

                 Close    High     Low        Volume
Date
2017-07-02  268.202162  293.73  253.23  8.084631e+07
2017-07-09  261.062083  285.00  231.25  2.246746e+08
2017-07-16  195.698393  240.33  130.26  5.017750e+08
2017-07-23  212.783750  249.40  153.25  7.221637e+08
2017-07-30  203.309524  229.99  178.03  2.657305e+08
...                ...     ...     ...           ...
2020-02-16  255.198452  290.00  216.31  3.912867e+08
2020-02-23  265.321905  287.13  242.36  3.067838e+08
2020-03-01  236.373988  278.13  209.26  3.693920e+08
2020-03-08  229.817619  253.01  196.00  2.736569e+08
2020-03-15  176.332821  208.65   90.00  4.983998e+08

[142 rows x 4 columns]